camunda:
  client:
    mode: saas
    auth:
      client-id: ${C8_CLIENT_ID}
      client-secret: ${C8_CLIENT_SECRET}
    cloud:
      cluster-id: ${C8_CLUSTER_ID}
      region: ${C8_CLUSTER_REGION}


zeebe:
  auth-server: https://login.cloud.camunda.io/oauth/token
  client-id: ${C8_CLIENT_ID}
  client-secret: ${C8_CLIENT_SECRET}


cluster:
  base-url: https://${C8_CLUSTER_REGION}.zeebe.camunda.io/${C8_CLUSTER_ID}/v2/